### ISSUE TITLE
README references prior non-rspec test script

### ISSUE THREAD

**Issue by paegun** [RedisGraph/redisgraph-rb#3]
README.md references prior non-rspec test script. Reviewing the commits to date, rspec was implemented along w/ circleci. Suggest: Update the README.md to reflect a local run of rspec to match how circleci runs the tests.

**Comment by paegun** [comment]
Proposed fix in #2 
This proposed fix also includes the information from #1 as to how to run the Redis server including the RedisGraph module 'graph' which matches the current client/module protocol of this client.

**Comment by jeffreylovitz** [comment]
Thanks for the PR, @paegun! I hope that the oversights in the README didn't cost you too much time - that and the other updates are welcome improvements.

**Comment by paegun** [comment]
@jeffreylovitz was/am looking into #1, so it cost me nearly no time. Thank you for RedisGraph. Closing since the README is now up-to-date.
